[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuration pour les redirections et les erreurs 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "nextjs"
  targetPort = 3000

# Configuration pour les fonctions Netlify
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
